plugins {
    id 'application'
    id 'java'
}

group = 'com.chatapp'
version = '1.0.0'

dependencies {
    implementation project(':common')
}

application {
    mainClass = 'com.chatapp.client.ui.Client' // Adjust the main class path as necessary
}

jar {
    manifest {
        attributes(
            'Main-Class': 'com.chatapp.client.ui.Client'
        )
    }
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

